version: "3.9"
services:
  badge:
    build:
      context: .
      dockerfile: ./action/Dockerfile
    entrypoint: ["uvicorn"]
    command: ["carbon_diff.badge:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
