name: Carbon Diff PR

on:
  pull_request:
    branches:
      - main

jobs:
  carbon:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # allow commenting on the PR

    steps:
      # 1 â–¸ Check out repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2 â–¸ Prepare Docker build context
      - name: Prepare Docker context
        run: |
          mkdir -p action/carbon_diff
          rsync -a carbon_diff/ action/carbon_diff/
          cp pyproject.toml poetry.lock README.md action/

      # 3 â–¸ Run the Docker Action (produces Î” JSON and writes to ledger)
      - name: Carbon diff
        id: diff
        uses: ./action
        env:
          CARBON_DB: ${{ github.workspace }}/.carbon/ledger.db

      # 4 â–¸ Comment on the PR with red/green Î” badge
      - name: Comment result
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DELTA_KWH=$(echo '${{ steps.diff.outputs }}' | jq '.kwh')
          if (( $(echo "$DELTA_KWH > 0" | bc -l) )); then COLOR="ðŸŸ¥"; else COLOR="ðŸŸ©"; fi
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "${COLOR} Î”kWh ${DELTA_KWH} (see docs)"

      # 5 â–¸ Install the carbon-diff CLI (so we can call carbon-record)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install carbon-diff CLI
        run: |
          pip install .

      # 6 â–¸ Persist a row in the ledger
      - name: Persist ledger
        run: |
          carbon-record \
            "${{ github.repository }}" \
            "${{ github.sha }}" \
            "${{ github.event.pull_request.number }}" \
            '${{ steps.diff.outputs }}'

      # 7 â–¸ (Optional) ensure FastAPI/sqlmodel deps are in place for any later tests
      - name: Install dependencies
        run: |
          pip install fastapi[all] sqlmodel aiosqlite
          pip install .
